### PR TITLE
Add Pandoc syntax highlighting files

### LINKED ISSUE #1: Pandoc syntax highlighting
As of Pandoc 2.0 I think, Pandoc uses the [Skylighting](https://github.com/jgm/skylighting) library. Currently this doesn't color SAS or Stata code. This library is used for PDF, HTML, and docx output, so it would be useful to have syntax highlighting. I think there are currently some filters around that you can use to use Pygments instead, but only for PDF output of course.

Have you seen a Stata syntax file that uses the KDE XML syntax? If not I'll probably start my own from scratch, but won't spend a crazy amount of time on it.

### PR DESCRIPTION
**Pull request by kylebarron**
The Stata syntax highlighter isn't perfect, but it's a start.

From:

- SAS: http://biostat.mc.vanderbilt.edu/wiki/Main/KateSasHighlighter
- Stata:
KDE/syntax-highlighting:data/syntax/stata.xml@master

Fixes #1

### CODE REVIEW

**Comment by kylebarron** [comment]
@mcaceresb Went to submit a new PR and realized I worked on the master branch the whole time. If you want me to separate the new stuff from the XML syntax highlighting files, I can.

Related to https://github.com/kylebarron/stata_kernel/issues/164

Colors
- functions without coloring the opening `(`
- nested macros
- I think has fallbacks for all scopes, so there should never be a lexer error.
- Highlights macros within strings
- It colors comments using the rules from `stata_kernel`, so those should be pretty accurate.

Doesn't try to highlight nested global macros, though that probably wouldn't take too long to implement if you thought it was worth it.

I can't attach an HTML so here's a screenshot
image

**Comment by kylebarron** [comment]
I still want to update at least the functions list with a more modern list.

**Comment by kylebarron** [comment]
Did you look at this revision?

**Comment by mcaceresb** [comment]
> Did you look at this revision?

No. It was item 2 in my list, after fixing the other issues with pygments... ``Un__n`` I def want to merge in the comment stuff, but I think the other changes are a different implementation of what I just pushed

**Comment by mcaceresb** [comment]
I'm looking at this now, so hold off a bit before making revisions (or let me know if you are changing sth).

**Comment by kylebarron** [comment]
I just made a slight change to allow nested globals. It seems cleaner at first glance than your code

**Comment by mcaceresb** [comment]
Almost surely; will have to figure out the merge conflicts.

**Comment by mcaceresb** [comment]
The library for pandoc is skylighting, yes?

**Comment by kylebarron** [comment]
Yes. I can remove that if you want. I forgot I had had that on the master branch too

**Comment by mcaceresb** [comment]
Wait, isn't that the main point of the PR? I was just going to rename the xml folder.

**Comment by kylebarron** [comment]
No... All the commits after the first two were for Pygments. But since I already had this PR open from my master branch to your master branch, I couldn't open a new one

**Comment by mcaceresb** [comment]
Ah, well, I was more keen on the pandoc stuff so that's why I didn't look at the pygments stuff first. Merging...

**Comment by kylebarron** [comment]
I didn't modify those XML files at all btw. I just copy and pasted them

**Comment by kylebarron** [comment]
Almost always with Pygments styles, `Name.Variable` and `Name.Variable.Global` are colored the same way, so I really didn't think it was worth the extra complexity to always highlight a local within a global and vice versa. 

Since a local will always end before the macro ends, and vice versa, just keep it simple.
```py
        'macros': [
            (r'\$\{', Name.Variable.Global, 'macro-global-braces'),
            (r'\$', Name.Variable.Global, 'macro-global'),
            (r'`', Name.Variable, 'macro-local'),
        ],
        'macro-global-braces': [
            (r'\$\{', Name.Variable.Global, '#push'),
            (r'}', Name.Variable.Global, '#pop'),
            (r'.', Name.Variable.Global),
        ],
        'macro-global': [
            (r'}', Name.Variable.Global, '#pop'),
            (r'\w(?![\w}])', Name.Variable.Global, '#pop'),
            (r'.', Name.Variable.Global),
        ],
        'macro-local': [
            (r'`', Name.Variable, '#push'),
            (r"'", Name.Variable, '#pop'),
            (r'.', Name.Variable),
        ],
```

**Comment by mcaceresb** [comment]
It wasn't really very complicated to do the nesting, unless I did it wrong.

Merging...

**Comment by mcaceresb** [comment]
Multi-line locals? Is that a thing? I guess it is in `#delimit`

**Comment by kylebarron** [comment]
Is it in delimit?

**Comment by mcaceresb** [comment]
No idea. But multi-line locals are getting highlighted.

**Comment by kylebarron** [comment]
Yes, but this was my point.

- It's important to highlight correct syntax correctly.
- It's not important to try to highlight incorrect syntax incorrectly.

Even with `#delimit;` I don't think multi-line locals work; or at least the `\n` counts as a space. But in _correct_ syntax, locals are finished on the same line, so we only have to think about that.

**Comment by kylebarron** [comment]
A couple other notes on your code:
> `(r'\\\\|\\"|\\\n', String.Escape)`

I don't think it's possible to escape a newline...

> ```py
> (r'(?<!\\)\$(\{|(?=[\$`]))', Name.Variable.Global, 'var_nestedglobal'),
> (r'(?<!\\)\$', Name.Variable.Global, 'var_validglobal'),
> (r'(?<!\\)`', Name.Variable, 'var_anylocal'),
> ```

No need to repeat the `(?<!\\)`. Just add `` \\\$|\\` `` to the escape regex.

**Comment by mcaceresb** [comment]
Don't really know how to merge a local branch here. I put all the things into `dev-panoc`. I think I'll just merge that to master. It's the same as this PR but I was working on it locally.

**Comment by mcaceresb** [comment]
It turns out git had CLI instructions at the bottom of the page.

**Pull request merged**
